In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("hr_dataset (1).csv")

In [4]:
data

satisfaction  evaluation  number_of_projects  average_montly_hours  \
0              0.38        0.53                   2                   157   
1              0.80        0.86                   5                   262   
2              0.11        0.88                   7                   272   
3              0.72        0.87                   5                   223   
4              0.37        0.52                   2                   159   
...             ...         ...                 ...                   ...   
14994          0.40        0.57                   2                   151   
14995          0.37        0.48                   2                   160   
14996          0.37        0.53                   2                   143   
14997          0.11        0.96                   6                   280   
14998          0.37        0.52                   2                   158   

       time_spend_company  work_accident  churn  promotion department  salary  
0                       3              0      1          0      sales     low  
1                       6              0      1          0      sales  medium  
2                       4              0      1          0      sales  medium  
3                       5              0      1          0      sales     low  
4                       3              0      1          0      sales     low  
...                   ...            ...    ...        ...        ...     ...  
14994                   3              0      1          0    support     low  
14995                   3              0      1          0    support     low  
14996                   3              0      1          0    support     low  
14997                   4              0      1          0    support     low  
14998                   3              0      1          0    support     low  

[14999 rows x 10 columns]

In [6]:
#CHECKING FOR NULL VALUES
data.isna().sum()

satisfaction            0
evaluation              0
number_of_projects      0
average_montly_hours    0
time_spend_company      0
work_accident           0
churn                   0
promotion               0
department              0
salary                  0
dtype: int64

In [8]:
#CHECKING  DATA TYPES

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   satisfaction          14999 non-null  float64
 1   evaluation            14999 non-null  float64
 2   number_of_projects    14999 non-null  int64  
 3   average_montly_hours  14999 non-null  int64  
 4   time_spend_company    14999 non-null  int64  
 5   work_accident         14999 non-null  int64  
 6   churn                 14999 non-null  int64  
 7   promotion             14999 non-null  int64  
 8   department            14999 non-null  object 
 9   salary                14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [17]:
#CHECKING RANGE OF VALUES

In [8]:
data.describe()

satisfaction    evaluation  number_of_projects  average_montly_hours  \
count  14999.000000  14999.000000        14999.000000          14999.000000   
mean       0.612834      0.716102            3.803054            201.050337   
std        0.248631      0.171169            1.232592             49.943099   
min        0.090000      0.360000            2.000000             96.000000   
25%        0.440000      0.560000            3.000000            156.000000   
50%        0.640000      0.720000            4.000000            200.000000   
75%        0.820000      0.870000            5.000000            245.000000   
max        1.000000      1.000000            7.000000            310.000000   

       time_spend_company  work_accident         churn     promotion  
count        14999.000000   14999.000000  14999.000000  14999.000000  
mean             3.498233       0.144610      0.238083      0.021268  
std              1.460136       0.351719      0.425924      0.144281  
min              2.000000       0.000000      0.000000      0.000000  
25%              3.000000       0.000000      0.000000      0.000000  
50%              3.000000       0.000000      0.000000      0.000000  
75%              4.000000       0.000000      0.000000      0.000000  
max             10.000000       1.000000      1.000000      1.000000

In [12]:
#SPLITTING DEPENDENT AND INDEPENDENT VARIABLE

In [9]:
y = data['churn']

In [10]:
x = data[['satisfaction', 'evaluation', 'number_of_projects',
       'average_montly_hours', 'time_spend_company', 'work_accident',
       'promotion', 'department', 'salary']]

In [1]:
#ENCODING
#SALARY - LABEL ENCODING
#DEPARTMENT - ONE HOT ENCODING

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [14]:
le.fit(x['salary'])

LabelEncoder()

In [15]:
le.classes_

array(['high', 'low', 'medium'], dtype=object)

In [16]:
#SPECIFYING ORDER FOR ENCODING SALARY VARIABLE
le.classes_ = np.array(["low","medium","high"])

In [18]:
x.loc[:,'salary'] = le.transform(x['salary'])

C:\Users\mebin\AppData\Local\Temp\ipykernel_1724\71468054.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.loc[:,'salary'] = le.transform(x['salary'])
C:\Users\mebin\AppData\Local\Temp\ipykernel_1724\71468054.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.loc[:,'salary'] = le.transform(x['salary'])


In [ ]:
#ONE HOT ENCODING FOR DEPARTMENT VARIABLE

In [21]:
x = pd.get_dummies(x)

In [ ]:
#SPLITTING TRAINING AND TESTING DATA

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size =0.2,random_state =32)

In [25]:
#CREATING INSTANCE OF ML MODEL - LOGISTIC REGRESSION

In [26]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [27]:
#FIT THE MODEL ON TRAINING DATA

In [28]:
lg.fit(x_train,y_train)

C:\Users\mebin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
#PREDICTION ON TEST DATA

In [30]:
y_pred = lg.predict(x_test)

In [31]:
#EVALUATING MODEL PERFORMANCE

In [37]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [33]:
acc = accuracy_score(y_test, y_pred)

In [34]:
print (acc)

0.798


In [35]:
confusion_matrix(y_test, y_pred)

array([[2126,  192],
       [ 414,  268]], dtype=int64)

In [38]:
precision = precision_score(y_test, y_pred)

In [39]:
print(precision)

0.5826086956521739


In [40]:
recall = recall_score(y_test, y_pred)

In [41]:
print(recall)

0.39296187683284456


In [42]:
f1 = f1_score(y_test, y_pred)

In [43]:
print(f1)

0.46935201401050786


In [44]:
#CROSS VALIDATED SCORE

In [45]:
from sklearn.model_selection import cross_val_score

In [46]:
cv_scores = cross_val_score (lg,x_train,y_train,cv = 5)

C:\Users\mebin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\mebin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [47]:
cv_scores

array([0.80625   , 0.79333333, 0.78958333, 0.79875   , 0.79908295])

In [48]:
cv_scores.mean()

0.7973999235792691

In [49]:
#CROSS VALIDATED SCORE FOR LOGISTIC REGRESSION MODEL IS 0.7973999235792691

In [50]:
#CREATING INSTANCE OF ML MODEL - KNN 

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
knn = KNeighborsClassifier(n_neighbors=9) 

In [53]:
#FIT THE MODEL ON TRAINING DATA
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [54]:
#PREDICTION ON TEST DATA
y_pred = knn.predict(x_test)

In [55]:
#EVALUATING MODEL PERFORMANCE

In [56]:
acc_knn = accuracy_score(y_test, y_pred)

In [57]:
print(acc_knn)

0.9356666666666666


In [58]:
confusion_matrix(y_test, y_pred)

array([[2169,  149],
       [  44,  638]], dtype=int64)

In [59]:
precision_knn = precision_score(y_test, y_pred)

In [60]:
print(precision_knn)

0.8106734434561627


In [61]:
recall_knn = recall_score(y_test, y_pred)

In [62]:
print(recall_knn)

0.9354838709677419


In [63]:
f1_knn = f1_score(y_test, y_pred)

In [64]:
print(f1_knn)

0.8686181075561608


In [65]:
#CROSS VALIDATED SCORE FOR KNN

In [67]:
cv_scores = cross_val_score (knn,x_train,y_train,cv = 5)

In [68]:
cv_scores

array([0.93416667, 0.94583333, 0.93583333, 0.92625   , 0.93789079])

In [69]:
cv_scores.mean()

0.9359948242323191

In [ ]:
#CROSS VALIDATED SCORE FOR KNN MODEL IS 0.9359948242323191